import feedparser
from datetime import datetime, timedelta
import os

# List of RSS feeds
rss_feeds = {
    "WordPress News": "http://wordpress.org/news/rss",
    # Add more RSS feeds here
}

# Get date 7 days ago
date_limit = datetime.now() - timedelta(days=7)

# Function to fetch articles from the feed
def fetch_feed_articles(feed_url):
    feed = feedparser.parse(feed_url)
    articles = []
    for entry in feed.entries:
        published = datetime(*entry.published_parsed[:6])
        if published > date_limit:
            articles.append((entry.title, entry.link))
    return articles

# Function to check if the article is already in the file
def is_article_already_added(article_title, file_content):
    return article_title in file_content

# Read the existing content of ARTICLES.md to avoid duplicating entries
existing_content = ""
if os.path.isfile('ARTICLES.md'):
    with open('ARTICLES.md', 'r') as file:
        existing_content = file.read()

markdown_content = ""
for title, url in rss_feeds.items():
    articles = fetch_feed_articles(url)
    if articles:
        markdown_content += f"## {title}\n"
        for article_title, article_link in articles:
            # Append only new articles
            if not is_article_already_added(article_title, existing_content):
                markdown_content += f"- [{article_title}]({article_link})\n"

# Append to the ARTICLES.md file
if markdown_content.strip() != "":
    with open('ARTICLES.md', 'a') as file:
        file.write(markdown_content)
