name: RSS Article Fetcher

on:
  schedule:
    - cron: '*/15 * * * *' # Runs every 15 minutes
  workflow_dispatch:

jobs:
  fetch-rss:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install feedparser
        
      - name: Fetch RSS Articles
        run: python fetch_rss.py
      
      - name: Commit and push if there are changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git pull --rebase # To ensure we are not behind the remote
          if [ -s ARTICLES.md ]; then
            git add ARTICLES.md
            git commit -m "Updated ARTICLES.md with new entries"
            git push
          else
            echo "No changes to ARTICLES.md"
          fi
